In [1]:
import pandas as pd
import numpy as np


In [2]:
import tensorflow
import keras
print(tensorflow.__version__)
print(keras.__version__)

2.13.0-rc1
2.13.1rc0


In [3]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist


In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data(path="mnist.npz")

In [55]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [56]:
x_train.shape


(60000, 28, 28)

In [57]:
width,height=28,28

In [58]:
input_shape=(width,height,1)

In [59]:
input_shape


(28, 28, 1)

In [60]:
x_train=x_train.reshape(x_train.shape[0],width,height,1)
x_test=x_test.reshape(x_test.shape[0],width,height,1)

In [61]:
x_train.shape

(60000, 28, 28, 1)

In [62]:
y_train.shape

(60000,)

In [63]:
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.1)

In [64]:
len(x_train)

54000

In [65]:
len(x_val)

6000

In [66]:
x_train=(x_train-x_train.mean()) / x_train.std()
x_test=(x_test-x_test.mean()) / x_test.std()
x_val=(x_val-x_val.mean()) / x_val.std()

In [67]:
x_train

array([[[[-0.42409215],
         [-0.42409215],
         [-0.42409215],
         ...,
         [-0.42409215],
         [-0.42409215],
         [-0.42409215]],

        [[-0.42409215],
         [-0.42409215],
         [-0.42409215],
         ...,
         [-0.42409215],
         [-0.42409215],
         [-0.42409215]],

        [[-0.42409215],
         [-0.42409215],
         [-0.42409215],
         ...,
         [-0.42409215],
         [-0.42409215],
         [-0.42409215]],

        ...,

        [[-0.42409215],
         [-0.42409215],
         [-0.42409215],
         ...,
         [-0.42409215],
         [-0.42409215],
         [-0.42409215]],

        [[-0.42409215],
         [-0.42409215],
         [-0.42409215],
         ...,
         [-0.42409215],
         [-0.42409215],
         [-0.42409215]],

        [[-0.42409215],
         [-0.42409215],
         [-0.42409215],
         ...,
         [-0.42409215],
         [-0.42409215],
         [-0.42409215]]],


       [[[-0.42409215],


In [68]:
num_labels=10
from tensorflow import keras

In [69]:
y_train=keras.utils.to_categorical(y_train)

In [70]:
y_test=keras.utils.to_categorical(y_test)
y_val=keras.utils.to_categorical(y_val)

In [71]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [72]:
#Model

In [73]:
from keras import layers


In [74]:
from keras.models import Sequential


In [75]:
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input, Conv2D, MaxPooling2D,AveragePooling2D

In [76]:
#lenit architecture
model=Sequential()
model.add(Conv2D(6,kernel_size=(5,5),strides=(1,1),activation='tanh',input_shape=(28,28,1)))
model.add(AveragePooling2D(pool_size=(2,2),strides=(1,1)))
model.add(Conv2D(16,kernel_size=(5,5),strides=(1,1),activation='tanh'))
model.add(AveragePooling2D(pool_size=(2,2),strides=(1,1)))
model.add(Conv2D(120,kernel_size=(5,5),strides=(1,1),activation='tanh'))

model.add(Flatten())
model.add(Dense(84,activation='tanh'))
model.add(Dense(num_labels,activation='softmax'))

In [77]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_11 (Conv2D)          (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d_6 (Avera  (None, 23, 23, 6)         0         
 gePooling2D)                                                    
                                                                 
 conv2d_12 (Conv2D)          (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_7 (Avera  (None, 18, 18, 16)        0         
 gePooling2D)                                                    
                                                                 
 conv2d_13 (Conv2D)          (None, 14, 14, 120)       48120     
                                                                 
 flatten_3 (Flatten)         (None, 23520)            

In [79]:
model.compile(loss=keras.losses.categorical_crossentropy,optimizer='adam',metrics=['accuracy'])

In [84]:
history=model.fit(x_train,y_train,batch_size=32,epochs=20,verbose=1, validation_data = (x_val,y_val))

Epoch 1/20
1688/1688 [==============================] - 38s 22ms/step - loss: 0.2955 - accuracy: 0.9121 - val_loss: 0.2101 - val_accuracy: 0.9382
Epoch 2/20
1688/1688 [==============================] - 37s 22ms/step - loss: 0.1939 - accuracy: 0.9411 - val_loss: 0.1920 - val_accuracy: 0.9420
Epoch 3/20
1688/1688 [==============================] - 37s 22ms/step - loss: 0.1720 - accuracy: 0.9471 - val_loss: 0.1665 - val_accuracy: 0.9507
Epoch 4/20
1688/1688 [==============================] - 37s 22ms/step - loss: 0.1529 - accuracy: 0.9538 - val_loss: 0.1607 - val_accuracy: 0.9510
Epoch 5/20
1688/1688 [==============================] - 38s 22ms/step - loss: 0.1515 - accuracy: 0.9535 - val_loss: 0.1619 - val_accuracy: 0.9505
Epoch 6/20
1688/1688 [==============================] - 37s 22ms/step - loss: 0.1437 - accuracy: 0.9553 - val_loss: 0.1356 - val_accuracy: 0.9580
Epoch 7/20
1688/1688 [==============================] - 37s 22ms/step - loss: 0.1288 - accuracy: 0.9608 - val_loss: 0.1478 -

In [85]:
score=model.evaluate(x_test,y_test,verbose=1)

313/313 [==============================] - 1s 4ms/step - loss: 0.1001 - accuracy: 0.9681


In [86]:
score

[0.10014894604682922, 0.9681000113487244]